apiVersion: iam.aws.upbound.io/v1beta1
kind: Policy
metadata:
  name: dynatrace-monitoring
spec:
  forProvider:
    description: Allow the Dynatrace Active Gate to access all necessary resources
    policy: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Action": [
              "acm-pca:ListCertificateAuthorities",
              "apigateway:GET",
              "apprunner:ListServices",
              "appstream:DescribeFleets",
              "appsync:ListGraphqlApis",
              "athena:ListWorkGroups",
              "autoscaling:DescribeAutoScalingGroups",
              "cloudformation:ListStackResources",
              "cloudfront:ListDistributions",
              "cloudhsm:DescribeClusters",
              "cloudsearch:DescribeDomains",
              "cloudwatch:GetMetricData",
              "cloudwatch:GetMetricStatistics",
              "cloudwatch:ListMetrics",
              "codebuild:ListProjects",
              "datasync:ListTasks",
              "dax:DescribeClusters",
              "directconnect:DescribeConnections",
              "dms:DescribeReplicationInstances",
              "dynamodb:ListTables",
              "dynamodb:ListTagsOfResource",
              "ec2:DescribeAvailabilityZones",
              "ec2:DescribeInstances",
              "ec2:DescribeNatGateways",
              "ec2:DescribeSpotFleetRequests",
              "ec2:DescribeTransitGateways",
              "ec2:DescribeVolumes",
              "ec2:DescribeVpnConnections",
              "ecs:ListClusters",
              "eks:ListClusters",
              "elasticache:DescribeCacheClusters",
              "elasticbeanstalk:DescribeEnvironmentResources",
              "elasticbeanstalk:DescribeEnvironments",
              "elasticfilesystem:DescribeFileSystems",
              "elasticloadbalancing:DescribeInstanceHealth",
              "elasticloadbalancing:DescribeListeners",
              "elasticloadbalancing:DescribeLoadBalancers",
              "elasticloadbalancing:DescribeRules",
              "elasticloadbalancing:DescribeTags",
              "elasticloadbalancing:DescribeTargetHealth",
              "elasticmapreduce:ListClusters",
              "elastictranscoder:ListPipelines",
              "es:ListDomainNames",
              "events:ListEventBuses",
              "firehose:ListDeliveryStreams",
              "fsx:DescribeFileSystems",
              "gamelift:ListFleets",
              "glue:GetJobs",
              "inspector:ListAssessmentTemplates",
              "kafka:ListClusters",
              "kinesis:ListStreams",
              "kinesisanalytics:ListApplications",
              "kinesisvideo:ListStreams",
              "lambda:ListFunctions",
              "lambda:ListTags",
              "lex:GetBots",
              "logs:DescribeLogGroups",
              "mediaconnect:ListFlows",
              "mediaconvert:DescribeEndpoints",
              "mediapackage-vod:ListPackagingConfigurations",
              "mediapackage:ListChannels",
              "mediatailor:ListPlaybackConfigurations",
              "opsworks:DescribeStacks",
              "qldb:ListLedgers",
              "rds:DescribeDBClusters",
              "rds:DescribeDBInstances",
              "rds:DescribeEvents",
              "rds:ListTagsForResource",
              "redshift:DescribeClusters",
              "robomaker:ListSimulationJobs",
              "route53:ListHostedZones",
              "route53resolver:ListResolverEndpoints",
              "s3:ListAllMyBuckets",
              "sagemaker:ListEndpoints",
              "sns:ListTopics",
              "sqs:ListQueues",
              "storagegateway:ListGateways",
              "sts:GetCallerIdentity",
              "swf:ListDomains",
              "tag:GetResources",
              "tag:GetTagKeys",
              "transfer:ListServers",
              "workmail:ListOrganizations",
              "workspaces:DescribeWorkspaces"
            ],
            "Resource": "*"
          }
        ]
      }