apiVersion: devopstoolkitseries.com/v1alpha1
kind: AppClaim
metadata:
  name: silly-demo
spec:
  id: silly-demo
  compositionSelector:
    matchLabels:
      type: backend-db
      location: remote
  parameters:
    namespace: production
    image: ghcr.io/vfarcic/silly-demo:1.4.113
    port: 8080
    host: silly-demo.54.204.223.4.nip.io
    kubernetesProviderConfigName: a-team-cluster
    dbSecret:
      name: my-db
