apiVersion: dynatrace.com/v1beta1
kind: DynaKube
metadata:
  name: app
  namespace: dynatrace
  annotations:
    feature.dynatrace.com/k8s-app-enabled: "true"
spec:
  apiUrl: https://ypd98635.sprint.dynatracelabs.com/api
  oneAgent:
    applicationMonitoring:
      useCSIDriver: true
  activeGate:
    capabilities:
      - kubernetes-monitoring
      - routing
    image: ""
    resources:
      requests:
        cpu: 500m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 1.5Gi
