---
apiVersion: devopstoolkitseries.com/v1alpha1
kind: SQLClaim
metadata:
  name: my-db
spec:
  id: my-db
  compositionSelector:
    matchLabels:
      provider: aws
      db: postgresql
  parameters:
    version: "14.10"
    size: medium
    databases:
      - my-db
    secrets:
      storeName: aws
      pullRootPasswordKey: db-password
      pushToStore: true
      pullToCluster: a-team-cluster
      pullToClusterNamespace: production
    dynatraceDashboard:
      enabled: true
      oathCredentialsSecretName: dynatrace-tokens
      cluster: a-team-cluster
      appDeploymentName: silly-demo
      appNamespace: production
    schemas:
      - database: my-db
        sql: |
          create table videos (
            id varchar(50) not null,
            title text,
            description text,
            primary key (id)
          );
          create table comments (
            id serial,
            video_id varchar(50) not null,
            description text not null,
            primary key (id),
            CONSTRAINT fk_videos FOREIGN KEY(video_id) REFERENCES videos(id)
          );
